const API = localStorage.getItem('pp-api') || '/api';
let token = localStorage.getItem('pp-token');
let user = JSON.parse(localStorage.getItem('pp-user') || 'null');
let page = 'dashboard';
let state = {};

const nav = {
 CUSTOMER:[['dashboard','Dashboard'],['projects','My Projects'],['build','Build Voucher'],['school','School Payment'],['transactions','Transactions'],['profile','Profile & KYC']],
 CONTRACTOR:[['dashboard','Dashboard'],['requests','Purchase Request'],['history','Purchase History']],
 MERCHANT:[['dashboard','Dashboard'],['verify','Verify Authorization'],['sales','Sales'],['settlements','Settlements']],
 ADMIN:[['dashboard','Control Center'],['kyc','KYC Review'],['transactions','Transactions'],['risk','Risk & Fraud'],['audit','Audit Logs']]
};
const money = n => new Intl.NumberFormat('en-GH',{style:'currency',currency:'GHS',maximumFractionDigits:2}).format(Number(n||0));
const esc = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge = s => `<span class="badge ${['VERIFIED','APPROVED','COMPLETED','ACTIVE','PARTIALLY_USED','CLEAR'].includes(s)?'success':['PENDING','UNDER_REVIEW','AUTHORIZED','REVIEW'].includes(s)?'warn':['FAILED','REJECTED','BLOCKED','VERIFICATION_FAILED'].includes(s)?'danger':'info'}">${esc(s)}</span>`;
function toast(msg,type='info'){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),3000)}
async function api(path,opts={}){
 const headers={'content-type':'application/json',...(opts.headers||{})}; if(token)headers.authorization=`Bearer ${token}`; if((opts.method||'GET').toUpperCase()!=='GET' && !headers['Idempotency-Key']) headers['Idempotency-Key']=crypto.randomUUID();
 const r=await fetch(`${API}${path}`,{...opts,headers}); const data=await r.json().catch(()=>({})); if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`); return data;
}
async function refresh(){
 if(!token)return;
 try{const m=await api('/me');user=m.user}catch(e){logout(false)}
}
function setSession(data){token=data.token;user=data.user;localStorage.setItem('pp-token',token);localStorage.setItem('pp-user',JSON.stringify(user));page='dashboard';render()}
function logout(show=true){token=null;user=null;localStorage.removeItem('pp-token');localStorage.removeItem('pp-user');if(show)toast('Signed out');render()}
function go(p){page=p;render()}
function layout(content){const r=user?.role||'CUSTOMER';return `<div class="shell"><aside class="sidebar"><div class="brand">Purpose<span>Pay</span></div><div class="nav">${(nav[r]||nav.CUSTOMER).map(([id,label])=>`<button class="${page===id?'active':''}" onclick="go('${id}')">${label}</button>`).join('')}</div><div class="sidebar-bottom"><div class="small">${esc(user?.firstName||'')} ${esc(user?.lastName||'')}</div><button class="nav button" onclick="logout()">Sign out</button></div></aside><main class="main"><header class="top"><div><b>${r[0]+r.slice(1).toLowerCase()} Portal</b><span class="muted"> · ${esc(API.replace('/api',''))}</span></div><div class="role">${esc(user?.email||'')}</div></header><section class="content">${content}</section></main></div>`}
function render(){document.getElementById('app').innerHTML=token&&user?layout(renderPage()):loginView()}
function loginView(){return `<div class="login"><div class="login-card"><div class="brand large">Purpose<span>Pay</span></div><p class="muted">Purpose-payment platform · connected MVP</p><form class="form" onsubmit="login(event)"><div class="field"><label>Email</label><input id="email" type="email" required value="demo@purposepay.test"></div><div class="field"><label>Password</label><input id="password" type="password" required value="Demo12345!"></div><button class="btn primary">Sign in</button></form><div class="demo-buttons"><button class="btn secondary" onclick="fillLogin('admin@purposepay.test','Admin12345!')">Admin demo</button><button class="btn secondary" onclick="fillLogin('merchant@purposepay.test','Merchant12345!')">Merchant demo</button><button class="btn secondary" onclick="fillLogin('contractor@purposepay.test','Contractor12345!')">Contractor demo</button></div><hr><h3>Create customer account</h3><form class="form" onsubmit="register(event)"><div class="row"><div class="field"><label>First name</label><input id="rf" required></div><div class="field"><label>Last name</label><input id="rl" required></div></div><div class="field"><label>Email</label><input id="re" type="email" required></div><div class="field"><label>Password</label><input id="rp" type="password" minlength="8" required></div><button class="btn secondary">Register</button></form><p class="muted tiny">Development build. No real money moves. KYC/payment integrations are not live.</p></div></div>`}
function fillLogin(e,p){document.getElementById('email').value=e;document.getElementById('password').value=p}
async function login(e){e.preventDefault();try{setSession(await api('/auth/login',{method:'POST',body:JSON.stringify({email:email.value,password:password.value})}))}catch(err){toast(err.message,'error')}}
async function register(e){e.preventDefault();try{setSession(await api('/auth/register',{method:'POST',body:JSON.stringify({firstName:rf.value,lastName:rl.value,email:re.value,password:rp.value})}));toast('Account created. Submit your government ID from Profile & KYC.')}catch(err){toast(err.message,'error')}}
async function renderPage(){
 const r=user.role;
 try{
  if(r==='CUSTOMER')return await customerPage();
  if(r==='CONTRACTOR')return await contractorPage();
  if(r==='MERCHANT')return await merchantPage();
  if(r==='ADMIN')return await adminPage();
 }catch(e){return `<div class="card error"><b>Could not load this page.</b><p>${esc(e.message)}</p><button class="btn secondary" onclick="render()">Retry</button></div>`}
}
// renderPage is async; render() handles it synchronously below.
async function mount(){document.getElementById('app').innerHTML=token&&user?layout(await renderPage()):loginView()}
render = mount;

async function customerPage(){
 if(page==='projects')return projectsView(); if(page==='build')return buildView(); if(page==='school')return schoolView(); if(page==='transactions')return transactionsView(); if(page==='profile')return profileView();
 const d=await api('/dashboard'); const v=await api('/vouchers'); return `<div class="hero"><h2>Support your family back home.</h2><p>Pay for specific things in Ghana without sending unrestricted cash.</p></div><div class="grid"><div class="card"><span class="label">Projects</span><div class="stat">${d.stats.projects}</div></div><div class="card"><span class="label">Vouchers</span><div class="stat">${d.stats.vouchers}</div></div><div class="card"><span class="label">Transactions</span><div class="stat">${d.stats.transactions}</div></div><div class="card"><span class="label">KYC</span><div class="stat">${badge(user.kycStatus)}</div></div></div><div class="grid2 gap"><div class="card"><h3>Build Voucher</h3><p class="muted">Restrict funds to a construction category and approved merchants.</p><button class="btn primary" onclick="go('build')">Create voucher</button></div><div class="card"><h3>School Payment</h3><p class="muted">Submit a direct payment to an approved school.</p><button class="btn secondary" onclick="go('school')">Pay school fees</button></div></div><div class="card gap"><h3>Recent vouchers</h3>${v.vouchers.length?table(['Code','Project','Category','Initial','Remaining','Status'],v.vouchers.slice(0,5).map(x=>[`PP-BLD-${x.id.slice(-8).toUpperCase()}`,x.project_name,x.category,money(x.initial_amount),money(x.remaining_amount),badge(x.status)])):empty('No vouchers yet.')}</div>`;
}
async function projectsView(){const r=await api('/projects');return `<div class="page-title"><h1>My Projects</h1><button class="btn primary" onclick="go('build')">+ New Project</button></div>${r.projects.map(p=>`<div class="card gap"><div class="page-title"><div><h3>${esc(p.name)}</h3><div class="muted">${esc(p.location)} · ${esc(p.contractor_name||'No contractor')}</div></div>${badge(p.status)}</div><p>${esc(p.description||'')}</p></div>`).join('')||empty('No projects yet.')}`}
async function buildView(){const projects=await api('/projects');return `<div class="page-title"><h1>Create Build Voucher</h1></div><div class="card"><div class="notice">Identity verification is required before a funded project can be created. Current KYC: ${badge(user.kycStatus)}</div><form class="form" onsubmit="createVoucher(event)"><div class="row"><div class="field"><label>Project name</label><input id="pn" required value="Johnson Family House"></div><div class="field"><label>Location</label><input id="pl" required value="Accra"></div></div><div class="row"><div class="field"><label>Contractor name</label><input id="cn" value="Kwame Mensah"></div><div class="field"><label>Contractor phone</label><input id="cp" value="+233 20 000 0000"></div></div><div class="row"><div class="field"><label>Category</label><select id="cat"><option>Cement</option><option>Blocks</option><option>Steel</option><option>Roofing</option><option>Plumbing</option><option>Electrical</option></select></div><div class="field"><label>Amount (GH₵)</label><input id="amt" type="number" min="1" step="1" required value="20000"></div></div><div class="field"><label>Project description</label><textarea id="pd">Construction materials for family house</textarea></div><div class="field"><label>Existing project</label><select id="projectId"><option value="">Create new project</option>${projects.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><button class="btn primary">Create purpose voucher</button></form></div>`}
async function createVoucher(e){e.preventDefault();try{let pid=projectId.value;if(!pid){const p=await api('/projects',{method:'POST',body:JSON.stringify({name:pn.value,location:pl.value,contractorName:cn.value,contractorPhone:cp.value,description:pd.value})});pid=p.id}const v=await api('/vouchers',{method:'POST',body:JSON.stringify({projectId:pid,category:cat.value,amount:Number(amt.value)})});toast(`Voucher ${v.code} created`);go('projects')}catch(err){toast(err.message,'error')}}
async function schoolView(){const s=await api('/schools');const p=await api('/schools/payments');return `<div class="page-title"><h1>School Payment</h1></div><div class="card"><form class="form" onsubmit="paySchool(event)"><div class="field"><label>School</label><select id="school">${s.schools.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><div class="row"><div class="field"><label>Student name</label><input id="student" required></div><div class="field"><label>Student ID</label><input id="studentId"></div></div><div class="row"><div class="field"><label>Term</label><input id="term" placeholder="2026/27 Term 1"></div><div class="field"><label>Amount (GH₵)</label><input id="schoolAmt" type="number" min="1" required></div></div><button class="btn primary">Submit school payment</button></form></div><div class="card gap"><h3>Payment history</h3>${table(['Reference','School','Student','Amount','Status'],p.payments.map(x=>[x.id,x.school_name,x.student_name,money(x.amount),badge(x.status)]))}</div>`}
async function paySchool(e){e.preventDefault();try{const r=await api('/schools/payments',{method:'POST',body:JSON.stringify({schoolId:school.value,studentName:student.value,studentId:studentId.value,term:term.value,amount:Number(schoolAmt.value)})});toast(`School payment ${r.id} submitted`);go('school')}catch(err){toast(err.message,'error')}}
async function transactionsView(){const r=await api('/transactions');return `<div class="page-title"><h1>Transactions</h1></div><div class="card table-wrap">${table(['Reference','Purpose','Merchant','Amount','Status','Settlement'],r.transactions.map(x=>[x.id,x.category||'School',x.merchant_name||'School',money(x.amount),badge(x.status),badge(x.settlement_status)]))}</div>`}
async function profileView(){const k=await api('/kyc/me');return `<div class="page-title"><h1>Profile & KYC</h1></div><div class="grid2"><div class="card"><h3>Account</h3><p><b>Name:</b> ${esc(user.firstName)} ${esc(user.lastName)}</p><p><b>Email:</b> ${esc(user.email)}</p><p><b>Phone:</b> ${esc(user.phone||'Not provided')}</p><p><b>KYC:</b> ${badge(user.kycStatus)}</p></div><div class="card"><h3>Government ID verification</h3>${k.kyc?`<p><b>Document:</b> ${esc(k.kyc.document_type)}</p><p><b>Number:</b> •••••${esc(k.kyc.document_number.slice(-4))}</p><p><b>Status:</b> ${badge(k.kyc.status)}</p>`:`<p class="muted">Submit your government ID to unlock funded payment activity.</p>`}<form class="form" onsubmit="submitKyc(event)"><div class="field"><label>Document type</label><select id="dtype"><option>Passport</option><option>National ID</option><option>Driver's Licence</option></select></div><div class="row"><div class="field"><label>Document number</label><input id="dnum" required></div><div class="field"><label>Country of issue</label><input id="dcountry" value="Ghana" required></div></div><div class="row"><div class="field"><label>Issue date</label><input id="dissue" type="date"></div><div class="field"><label>Expiry date</label><input id="dexpiry" type="date"></div></div><button class="btn primary">Submit for review</button></form></div></div>`}
async function submitKyc(e){e.preventDefault();try{await api('/kyc/submit',{method:'POST',body:JSON.stringify({documentType:dtype.value,documentNumber:dnum.value,countryOfIssue:dcountry.value,issueDate:dissue.value,expiryDate:dexpiry.value})});user.kycStatus='UNDER_REVIEW';localStorage.setItem('pp-user',JSON.stringify(user));toast('KYC submitted for review');go('profile')}catch(err){toast(err.message,'error')}}
async function contractorPage(){if(page==='history')return transactionsView();const v=await api('/vouchers');const m=await api('/merchants');if(page==='requests')return `<div class="page-title"><h1>Purchase Request</h1></div><div class="card"><form class="form" onsubmit="authorizePurchase(event)"><div class="field"><label>Voucher</label><select id="voucher">${v.vouchers.map(x=>`<option value="${x.id}">${x.project_name} · ${x.category} · ${money(x.remaining_amount)} remaining</option>`).join('')}</select></div><div class="field"><label>Approved merchant</label><select id="merchantId">${m.merchants.map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.categories.join(', '))}</option>`).join('')}</select></div><div class="field"><label>Amount (GH₵)</label><input id="purchaseAmt" type="number" min="1" required value="1000"></div><button class="btn primary">Request authorization</button></form></div>`;return `<div class="page-title"><h1>Contractor Dashboard</h1></div><div class="grid"><div class="card"><span class="label">Available vouchers</span><div class="stat">${v.vouchers.length}</div></div><div class="card"><span class="label">Role</span><div class="stat">Contractor</div></div></div><div class="card gap"><h3>Controlled purchasing</h3><p class="muted">Select an approved voucher and merchant, then receive a one-time authorization code.</p><button class="btn primary" onclick="go('requests')">Create purchase request</button></div>`}
async function authorizePurchase(e){e.preventDefault();try{const r=await api('/transactions/authorize',{method:'POST',body:JSON.stringify({voucherId:voucher.value,merchantId:merchantId.value,amount:Number(purchaseAmt.value)})});toast(`Authorized: ${r.authorizationCode}`);go('history')}catch(err){toast(err.message,'error')}}
async function merchantPage(){const tx=await api('/transactions');if(page==='sales')return `<div class="page-title"><h1>Sales</h1></div><div class="card table-wrap">${table(['Reference','Customer','Purpose','Amount','Status','Risk'],tx.transactions.map(x=>[x.id,x.customer_email||'',x.category,money(x.amount),badge(x.status),badge(x.risk_status)]))}</div>`;if(page==='settlements')return `<div class="page-title"><h1>Settlements</h1></div><div class="card"><p class="muted">Settlement records remain controlled by the payment/settlement integration. Demo transactions are marked pending.</p></div>`;if(page==='verify')return `<div class="page-title"><h1>Verify & Complete Authorization</h1></div><div class="card"><form class="form" onsubmit="completeSale(event)"><div class="field"><label>Transaction ID</label><input id="txid" required></div><div class="field"><label>Authorization code</label><input id="auth" required></div><div class="field"><label>Receipt URL (demo)</label><input id="receipt" placeholder="https://... or internal receipt reference"></div><button class="btn primary">Complete sale</button></form></div>`;return `<div class="page-title"><h1>Merchant Dashboard</h1></div><div class="grid"><div class="card"><span class="label">Transactions</span><div class="stat">${tx.transactions.length}</div></div><div class="card"><span class="label">Completed value</span><div class="stat">${money(tx.transactions.filter(x=>x.status==='COMPLETED').reduce((a,x)=>a+x.amount,0))}</div></div></div><div class="card gap"><h3>Process a PurposePay authorization</h3><p class="muted">Never complete a sale unless the authorization is valid and the purchase matches the approved purpose.</p><button class="btn primary" onclick="go('verify')">Verify authorization</button></div>`}
async function completeSale(e){e.preventDefault();try{const r=await api('/transactions/complete',{method:'POST',body:JSON.stringify({transactionId:txid.value,authorizationCode:auth.value,receiptUrl:receipt.value})});toast(`Sale ${r.status.toLowerCase()}`);go('sales')}catch(err){toast(err.message,'error')}}
async function adminPage(){if(page==='kyc')return adminKyc();if(page==='transactions')return `<div class="page-title"><h1>Transaction Monitoring</h1></div><div class="card table-wrap">${table(['Reference','Customer','Merchant','Amount','Status','Risk'],(await api('/transactions')).transactions.map(x=>[x.id,x.customer_email,x.merchant_name||'',money(x.amount),badge(x.status),badge(x.risk_status)]))}</div>`;if(page==='risk')return adminRisk();if(page==='audit'){const r=await api('/admin/audit');return `<div class="page-title"><h1>Audit Logs</h1></div><div class="card table-wrap">${table(['Time','Action','Entity','ID'],r.logs.map(x=>[x.created_at,x.action,x.entity_type,x.entity_id||'']))}</div>`}const d=await api('/dashboard');return `<div class="page-title"><h1>Admin Control Center</h1></div><div class="grid"><div class="card"><span class="label">Customers</span><div class="stat">${d.stats.customers}</div></div><div class="card"><span class="label">Pending KYC</span><div class="stat">${d.stats.pendingKyc}</div></div><div class="card"><span class="label">Transactions</span><div class="stat">${d.stats.transactions}</div></div><div class="card"><span class="label">Open risk</span><div class="stat">${d.stats.openRisk}</div></div></div><div class="grid2 gap"><div class="card"><h3>KYC Review</h3><p class="muted">Review identity submissions and record an auditable decision.</p><button class="btn primary" onclick="go('kyc')">Open KYC queue</button></div><div class="card"><h3>Risk & Fraud</h3><p class="muted">Review high-value and flagged transactions.</p><button class="btn secondary" onclick="go('risk')">Open risk center</button></div></div>`}
async function adminKyc(){const r=await api('/admin/kyc');return `<div class="page-title"><h1>KYC Review</h1></div>${r.documents.map(x=>`<div class="card gap"><div class="page-title"><div><h3>${esc(x.first_name)} ${esc(x.last_name)}</h3><div class="muted">${esc(x.email)} · ${esc(x.document_type)} · •••••${esc(x.document_number.slice(-4))}</div></div>${badge(x.status)}</div><p>Country: ${esc(x.country_of_issue)} · Submitted: ${esc(x.created_at)}</p><div class="actions"><button class="btn success" onclick="reviewKyc('${x.id}','VERIFIED')">Approve</button><button class="btn danger" onclick="reviewKyc('${x.id}','FAILED')">Reject</button></div></div>`).join('')||empty('No KYC submissions.')}`}
async function reviewKyc(id,status){try{await api(`/admin/kyc/${id}/review`,{method:'POST',body:JSON.stringify({status})});toast(`KYC ${status.toLowerCase()}`);go('kyc')}catch(e){toast(e.message,'error')}}
async function adminRisk(){const r=await api('/admin/risk');return `<div class="page-title"><h1>Risk & Fraud</h1></div>${r.alerts.map(x=>`<div class="card gap"><div class="page-title"><div><h3>${esc(x.id)}</h3><div class="muted">${esc(x.customer_email)} · ${esc(x.merchant_name||'')} · ${money(x.amount)}</div></div>${badge(x.risk_status)}</div><p>Purpose: ${esc(x.category)} · Transaction: ${esc(x.id)}</p><button class="btn success" onclick="resolveRisk('${x.id}','CLEAR')">Mark reviewed</button><button class="btn danger" onclick="resolveRisk('${x.id}','BLOCKED')">Block</button></div>`).join('')||empty('No flagged transactions.')}`}
async function resolveRisk(id,status){try{await api('/admin/risk/resolve',{method:'POST',body:JSON.stringify({transactionId:id,status})});toast(`Risk status: ${status}`);go('risk')}catch(e){toast(e.message,'error')}}
function table(headers,rows){if(!rows.length)return empty('No records.');return `<table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function empty(msg){return `<div class="empty">${esc(msg)}</div>`}

mount();