const API = localStorage.getItem('pp-api') || '/api';
let token = localStorage.getItem('pp-token');
let user = JSON.parse(localStorage.getItem('pp-user') || 'null');
let page = 'dashboard';
let state = {};

const nav = {
 CUSTOMER:[['dashboard','Dashboard'],['funding','Add Funds'],['projects','My Projects'],['build','Build Voucher'],['school','School Payment'],['transactions','Transactions'],['profile','Profile & KYC'],['disputes','Disputes']],
 CONTRACTOR:[['dashboard','Dashboard'],['requests','Purchase Request'],['history','Purchase History']],
 MERCHANT:[['dashboard','Dashboard'],['onboarding','Business Onboarding'],['payout','Payout Account'],['verify','Verify Authorization'],['sales','Sales'],['settlements','Settlements']],
 ADMIN:[['dashboard','Control Center'],['operations','Operations'],['financial','Financial Integrity'],['reconexceptions','Recon Exceptions'],['kyc','KYC Review'],['transactions','Transactions'],['disputes','Disputes'],['settlements','Settlements'],['reconciliation','Reconciliation'],['risk','Risk & Fraud'],['audit','Audit Logs']]
};
const money = n => new Intl.NumberFormat('en-GH',{style:'currency',currency:'GHS',maximumFractionDigits:2}).format(Number(n||0));
const esc = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge = s => `<span class="badge ${['VERIFIED','APPROVED','COMPLETED','ACTIVE','PARTIALLY_USED','CLEAR'].includes(s)?'success':['PENDING','UNDER_REVIEW','AUTHORIZED','REVIEW'].includes(s)?'warn':['FAILED','REJECTED','BLOCKED','VERIFICATION_FAILED'].includes(s)?'danger':'info'}">${esc(s)}</span>`;
function toast(msg,type='info'){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),3000)}
async function api(path,opts={}){
 const headers={'content-type':'application/json',...(opts.headers||{})}; if(token)headers.authorization=`Bearer ${token}`; if((opts.method||'GET').toUpperCase()!=='GET' && !headers['Idempotency-Key']) headers['Idempotency-Key']=crypto.randomUUID();
 const r=await fetch(`${API}${path}`,{...opts,headers}); const data=await r.json().catch(()=>({})); if(r.status===401 && path!=='/auth/login' && path!=='/auth/register'){token=null;user=null;localStorage.removeItem('pp-token');localStorage.removeItem('pp-user');throw new Error('Your session has expired. Please sign in again.')} if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`); return data;
}
async function refresh(){
 if(!token)return;
 try{const m=await api('/me');user=m.user}catch(e){logout(false)}
}
function setSession(data){token=data.token;user=data.user;localStorage.setItem('pp-token',token);localStorage.setItem('pp-user',JSON.stringify(user));page='dashboard';render()}
function logout(show=true){token=null;user=null;localStorage.removeItem('pp-token');localStorage.removeItem('pp-user');if(show)toast('Signed out');render()}
function go(p){page=p;render()}
function layout(content){const r=user?.role||'CUSTOMER';return `<div class="shell"><aside class="sidebar"><div class="brand">Purpose<span>Pay</span></div><div class="nav">${(nav[r]||nav.CUSTOMER).map(([id,label])=>`<button class="${page===id?'active':''}" onclick="go('${id}')">${label}</button>`).join('')}</div><div class="sidebar-bottom"><div class="small">${esc(user?.firstName||'')} ${esc(user?.lastName||'')}</div><button class="nav button" onclick="logout()">Sign out</button></div></aside><main class="main"><header class="top"><div><b>${r[0]+r.slice(1).toLowerCase()} Portal</b><span class="muted"> · ${esc(API.replace('/api',''))}</span></div><div class="role">${esc(user?.email||'')}</div></header><section class="content">${content}</section></main></div>`}
function render(){document.getElementById('app').innerHTML=token&&user?layout(renderPage()):loginView()}
function loginView(){return `<div class="login"><div class="login-card"><div class="brand large">Purpose<span>Pay</span></div><p class="muted">Purpose-payment platform · connected MVP</p><form class="form" onsubmit="login(event)"><div class="field"><label>Email</label><input id="email" type="email" required value="demo@purposepay.test"></div><div class="field"><label>Password</label><input id="password" type="password" required value="Demo12345!"></div><button class="btn primary">Sign in</button></form><div class="demo-buttons"><button class="btn secondary" onclick="fillLogin('admin@purposepay.test','Admin12345!')">Admin demo</button><button class="btn secondary" onclick="fillLogin('merchant@purposepay.test','Merchant12345!')">Merchant demo</button><button class="btn secondary" onclick="fillLogin('contractor@purposepay.test','Contractor12345!')">Contractor demo</button></div><hr><h3>Create customer account</h3><form class="form" onsubmit="register(event)"><div class="row"><div class="field"><label>First name</label><input id="rf" required></div><div class="field"><label>Last name</label><input id="rl" required></div></div><div class="field"><label>Email</label><input id="re" type="email" required></div><div class="field"><label>Password</label><input id="rp" type="password" minlength="8" required></div><div class="row"><div class="field"><label>Government ID type</label><select id="rdt" required><option value="">Select document</option><option>Passport</option><option>National ID</option><option>Driver's Licence</option></select></div><div class="field"><label>Government ID number</label><input id="rdn" required autocomplete="off"></div></div><div class="field"><label>Country of issue</label><input id="rdc" value="Ghana" required></div><div class="row"><div class="field"><label>Issue date</label><input id="rdi" type="date"></div><div class="field"><label>Expiry date</label><input id="rde" type="date"></div></div><div class="notice">Your government ID details are submitted for KYC review. Do not enter banking passwords or payment-card details.</div><button class="btn secondary">Register & submit ID</button></form><p class="muted tiny">Development build. No real money moves. KYC/payment integrations are not live.</p></div></div>`}
function fillLogin(e,p){document.getElementById('email').value=e;document.getElementById('password').value=p}
async function login(e){e.preventDefault();try{setSession(await api('/auth/login',{method:'POST',body:JSON.stringify({email:email.value,password:password.value})}))}catch(err){toast(err.message,'error')}}
async function register(e){e.preventDefault();try{setSession(await api('/auth/register',{method:'POST',body:JSON.stringify({firstName:rf.value,lastName:rl.value,email:re.value,password:rp.value,documentType:rdt.value,documentNumber:rdn.value,countryOfIssue:rdc.value,issueDate:rdi.value,expiryDate:rde.value})}));toast('Account created. Government ID submitted for KYC review.')}catch(err){toast(err.message,'error')}}
async function renderPage(){
 const r=user.role;
 try{
  if(r==='CUSTOMER')return await customerPage();
  if(r==='CONTRACTOR')return await contractorPage();
  if(r==='MERCHANT')return await merchantPage();
  if(r==='ADMIN')return await adminPage();
 }catch(e){if(!token||!user)return loginView();return `<div class="card error"><b>Could not load this page.</b><p>${esc(e.message)}</p><button class="btn secondary" onclick="render()">Retry</button></div>`}
}
// renderPage is async; render() handles it synchronously below.
async function mount(){if(token&&user){await refresh();if(!token||!user){document.getElementById('app').innerHTML=loginView();return}document.getElementById('app').innerHTML=layout(await renderPage());return}document.getElementById('app').innerHTML=loginView()}
render = mount;

async function customerPage(){
 if(page==='funding')return fundingView(); if(page==='projects')return projectsView(); if(page==='build')return buildView(); if(page==='school')return schoolView(); if(page==='transactions')return transactionsView(); if(page==='profile')return profileView(); if(page==='disputes')return disputesView(); if(page==='notifications')return notificationsView();
 const d=await api('/dashboard'); const v=await api('/vouchers'); return `<div class="hero"><h2>Support your family back home.</h2><p>Pay for specific things in Ghana without sending unrestricted cash.</p></div><div class="grid"><div class="card"><span class="label">Projects</span><div class="stat">${d.stats.projects}</div></div><div class="card"><span class="label">Vouchers</span><div class="stat">${d.stats.vouchers}</div></div><div class="card"><span class="label">Transactions</span><div class="stat">${d.stats.transactions}</div></div><div class="card"><span class="label">KYC</span><div class="stat">${badge(user.kycStatus)}</div></div></div><div class="grid2 gap"><div class="card"><h3>Build Voucher</h3><p class="muted">Restrict funds to a construction category and approved merchants.</p><button class="btn primary" onclick="go('build')">Create voucher</button></div><div class="card"><h3>School Payment</h3><p class="muted">Submit a direct payment to an approved school.</p><button class="btn secondary" onclick="go('school')">Pay school fees</button></div></div><div class="card gap"><h3>Recent vouchers</h3>${v.vouchers.length?table(['Code','Project','Category','Initial','Remaining','Status'],v.vouchers.slice(0,5).map(x=>[`PP-BLD-${x.id.slice(-8).toUpperCase()}`,x.project_name,x.category,money(x.initial_amount),money(x.remaining_amount),badge(x.status)])):empty('No vouchers yet.')}</div>`;
}
async function inviteContractor(e,projectId){e.preventDefault();const input=document.getElementById('invite-'+projectId);try{await api('/projects/'+projectId+'/contractors/invite',{method:'POST',body:JSON.stringify({contractorEmail:input.value})});toast('Contractor invitation sent');go('projects')}catch(err){toast(err.message,'error')}}
async function verifyContractor(assignmentId,projectId){try{await api('/projects/'+projectId+'/contractors/'+assignmentId+'/verify',{method:'POST',body:JSON.stringify({status:'VERIFIED'})});toast('Contractor verified');go('projects')}catch(e){toast(e.message,'error')}}
async function projectsView(){const r=await api('/projects');return '<div class="page-title"><h1>My Projects</h1><button class="btn primary" onclick="go(\'build\')">+ New Project</button></div>'+r.projects.map(p=>'<div class="card gap"><div class="page-title"><div><h3>'+esc(p.name)+'</h3><div class="muted">'+esc(p.location)+' · '+esc(p.contractor_name||'No contractor')+'</div></div>'+badge(p.status)+'</div><p>'+esc(p.description||'')+'</p><form class="inline-form" onsubmit="inviteContractor(event,\''+p.id+'\')"><input id="invite-'+p.id+'" type="email" required placeholder="Contractor email"><button class="btn secondary">Invite / re-invite contractor</button></form><p class="tiny muted">Contractor must accept the invitation before you can verify the assignment.</p></div>').join('')||empty('No projects yet.')}
async function buildView(){const projects=await api('/projects');return `<div class="page-title"><h1>Create Build Voucher</h1></div><div class="card"><div class="notice">Identity verification is required before a funded project can be created. Current KYC: ${badge(user.kycStatus)}</div><form class="form" onsubmit="createVoucher(event)"><div class="row"><div class="field"><label>Project name</label><input id="pn" required value="Johnson Family House"></div><div class="field"><label>Location</label><input id="pl" required value="Accra"></div></div><div class="row"><div class="field"><label>Contractor name</label><input id="cn" value="Kwame Mensah"></div><div class="field"><label>Contractor phone</label><input id="cp" value="+233 20 000 0000"></div><div class="field"><label>Contractor email</label><input id="ce" type="email" placeholder="contractor@example.com"></div></div><div class="row"><div class="field"><label>Category</label><select id="cat"><option>Cement</option><option>Blocks</option><option>Steel</option><option>Roofing</option><option>Plumbing</option><option>Electrical</option></select></div><div class="field"><label>Amount (GH₵)</label><input id="amt" type="number" min="1" step="1" required value="20000"></div></div><div class="field"><label>Project description</label><textarea id="pd">Construction materials for family house</textarea></div><div class="field"><label>Existing project</label><select id="projectId"><option value="">Create new project</option>${projects.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><button class="btn primary">Create purpose voucher</button></form></div>`}
async function createVoucher(e){e.preventDefault();try{let pid=projectId.value;if(!pid){const p=await api('/projects',{method:'POST',body:JSON.stringify({name:pn.value,location:pl.value,contractorName:cn.value,contractorPhone:cp.value,description:pd.value})});pid=p.id;if(ce.value)await api('/projects/'+pid+'/contractors/invite',{method:'POST',body:JSON.stringify({contractorEmail:ce.value})})}const v=await api('/vouchers',{method:'POST',body:JSON.stringify({projectId:pid,category:cat.value,amount:Number(amt.value)})});toast(`Voucher ${v.code} created`);go('projects')}catch(err){toast(err.message,'error')}}
async function schoolView(){const s=await api('/schools');const p=await api('/schools/payments');return `<div class="page-title"><h1>School Payment</h1></div><div class="card"><form class="form" onsubmit="paySchool(event)"><div class="field"><label>School</label><select id="school">${s.schools.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><div class="row"><div class="field"><label>Student name</label><input id="student" required></div><div class="field"><label>Student ID</label><input id="studentId"></div></div><div class="row"><div class="field"><label>Term</label><input id="term" placeholder="2026/27 Term 1"></div><div class="field"><label>Amount (GH₵)</label><input id="schoolAmt" type="number" min="1" required></div></div><button class="btn primary">Submit school payment</button></form></div><div class="card gap"><h3>Payment history</h3>${table(['Reference','School','Student','Amount','Status'],p.payments.map(x=>[x.id,x.school_name,x.student_name,money(x.amount),badge(x.status)]))}</div>`}
async function paySchool(e){e.preventDefault();try{const r=await api('/schools/payments',{method:'POST',body:JSON.stringify({schoolId:school.value,studentName:student.value,studentId:studentId.value,term:term.value,amount:Number(schoolAmt.value)})});toast(`School payment ${r.id} submitted`);go('school')}catch(err){toast(err.message,'error')}}
async function transactionsView(){const r=await api('/transactions');return '<div class="page-title"><h1>Transactions</h1></div><div class="card table-wrap">'+table(['Reference','Purpose','Merchant','Amount','Status','Settlement','Actions'],r.transactions.map(x=>{const actions=x.status==='COMPLETED'?'<button class="btn secondary" onclick="viewReceipt(&quot;'+x.id+'&quot;)">Receipt</button> <button class="btn secondary" onclick="openDispute(&quot;'+x.id+'&quot;)">Dispute</button>':'';return [x.id,x.category||'School',x.merchant_name||'School',money(x.amount),badge(x.status),badge(x.settlement_status),actions]}))+'</div>'}
async function openDispute(id){const reason=prompt('Reason for dispute');if(!reason)return;const details=prompt('Additional details (optional)')||'';try{await api('/transactions/'+id+'/dispute',{method:'POST',body:JSON.stringify({reason:reason,details:details})});toast('Dispute opened');go('disputes')}catch(e){toast(e.message,'error')}}
async function profileView(){const k=await api('/kyc/me');return `<div class="page-title"><h1>Profile & KYC</h1></div><div class="grid2"><div class="card"><h3>Account</h3><p><b>Name:</b> ${esc(user.firstName)} ${esc(user.lastName)}</p><p><b>Email:</b> ${esc(user.email)}</p><p><b>Phone:</b> ${esc(user.phone||'Not provided')}</p><p><b>KYC:</b> ${badge(user.kycStatus)}</p></div><div class="card"><h3>Government ID verification</h3>${k.kyc?`<p><b>Document:</b> ${esc(k.kyc.document_type)}</p><p><b>Number:</b> •••••${esc(k.kyc.documentNumberLast4||'****')}</p><p><b>Status:</b> ${badge(k.kyc.status)}</p>`:`<p class="muted">Submit your government ID to unlock funded payment activity.</p>`}<form class="form" onsubmit="submitKyc(event)"><div class="field"><label>Document type</label><select id="dtype"><option>Passport</option><option>National ID</option><option>Driver's Licence</option></select></div><div class="row"><div class="field"><label>Document number</label><input id="dnum" required></div><div class="field"><label>Country of issue</label><input id="dcountry" value="Ghana" required></div></div><div class="row"><div class="field"><label>Issue date</label><input id="dissue" type="date"></div><div class="field"><label>Expiry date</label><input id="dexpiry" type="date"></div></div><button class="btn primary">Submit for review</button></form></div></div>`}
async function submitKyc(e){e.preventDefault();try{await api('/kyc/submit',{method:'POST',body:JSON.stringify({documentType:dtype.value,documentNumber:dnum.value,countryOfIssue:dcountry.value,issueDate:dissue.value,expiryDate:dexpiry.value})});user.kycStatus='UNDER_REVIEW';localStorage.setItem('pp-user',JSON.stringify(user));toast('KYC submitted for review');go('profile')}catch(err){toast(err.message,'error')}}
async function contractorRequestsView(){const projects=await api('/projects');let blocks=[];for(const p of projects.projects||[]){try{const cs=(await api('/projects/'+p.id+'/contractors')).contractors||[];for(const x of cs.filter(y=>y.contractor_id===user.id)){blocks.push('<div class="card gap"><h3>'+esc(p.name)+'</h3><p class="muted">'+esc(p.location)+' · '+esc(p.description||'')+'</p><p>Status: '+badge(x.status)+'</p>'+(x.status==='INVITED'?'<div class="actions"><button class="btn success" onclick="respondContractor(\''+p.id+'\',\''+x.id+'\',\'ACCEPTED\')">Accept</button><button class="btn danger" onclick="respondContractor(\''+p.id+'\',\''+x.id+'\',\'DECLINED\')">Decline</button></div>':x.status==='ACCEPTED'?'<div class="notice">Accepted. The project owner must verify you before voucher purchases are authorized.</div>':x.status==='VERIFIED'?'<div class="notice">Verified. You can now use authorized project vouchers.</div>':'')+'</div>')}}catch(e){}}return '<div class="page-title"><h1>Project Requests</h1></div>'+blocks.join('')||empty('No contractor project requests.')}
async function respondContractor(projectId,assignmentId,status){try{await api('/projects/'+projectId+'/contractors/'+assignmentId+'/respond',{method:'POST',body:JSON.stringify({status:status})});toast('Project request '+status.toLowerCase());go('requests')}catch(e){toast(e.message,'error')}}
async function contractorPage(){if(page==='history')return transactionsView();if(page==='requests')return contractorRequestsView();const v=await api('/vouchers');const m=await api('/merchants');if(page==='requests')return `<div class="page-title"><h1>Purchase Request</h1></div><div class="card"><form class="form" onsubmit="authorizePurchase(event)"><div class="field"><label>Voucher</label><select id="voucher">${v.vouchers.map(x=>`<option value="${x.id}">${x.project_name} · ${x.category} · ${money(x.remaining_amount)} remaining</option>`).join('')}</select></div><div class="field"><label>Approved merchant</label><select id="merchantId">${m.merchants.map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.categories.join(', '))}</option>`).join('')}</select></div><div class="field"><label>Amount (GH₵)</label><input id="purchaseAmt" type="number" min="1" required value="1000"></div><button class="btn primary">Request authorization</button></form></div>`;return `<div class="page-title"><h1>Contractor Dashboard</h1></div><div class="grid"><div class="card"><span class="label">Available vouchers</span><div class="stat">${v.vouchers.length}</div></div><div class="card"><span class="label">Role</span><div class="stat">Contractor</div></div></div><div class="card gap"><h3>Controlled purchasing</h3><p class="muted">Select an approved voucher and merchant, then receive a one-time authorization code.</p><button class="btn primary" onclick="go('requests')">Create purchase request</button></div>`}
async function authorizePurchase(e){e.preventDefault();try{const r=await api('/transactions/authorize',{method:'POST',body:JSON.stringify({voucherId:voucher.value,merchantId:merchantId.value,amount:Number(purchaseAmt.value)})});toast(`Authorized: ${r.authorizationCode}`);go('history')}catch(err){toast(err.message,'error')}}
async function merchantPage(){const tx=await api('/transactions');if(page==='onboarding')return merchantOnboardingView();if(page==='payout')return merchantPayoutView();if(page==='sales')return `<div class="page-title"><h1>Sales</h1></div><div class="card table-wrap">${table(['Reference','Customer','Purpose','Amount','Status','Risk'],tx.transactions.map(x=>[x.id,x.customer_email||'',x.category,money(x.amount),badge(x.status),badge(x.risk_status)]))}</div>`;if(page==='settlements'){const r=await api('/settlements');return `<div class="page-title"><h1>Settlements</h1></div><div class="card table-wrap">${table(['Reference','Amount','Status','Created'],r.settlements.map(x=>[x.id,money(x.amount),badge(x.status),esc(x.created_at)]))}</div>`;}if(page==='verify')return `<div class="page-title"><h1>Verify & Complete Authorization</h1></div><div class="card"><form class="form" onsubmit="completeSale(event)"><div class="field"><label>Transaction ID</label><input id="txid" required></div><div class="field"><label>Authorization code</label><input id="auth" required></div><div class="field"><label>Receipt URL (demo)</label><input id="receipt" placeholder="https://... or internal receipt reference"></div><button class="btn primary">Complete sale</button></form></div>`;return `<div class="page-title"><h1>Merchant Dashboard</h1></div><div class="grid"><div class="card"><span class="label">Transactions</span><div class="stat">${tx.transactions.length}</div></div><div class="card"><span class="label">Completed value</span><div class="stat">${money(tx.transactions.filter(x=>x.status==='COMPLETED').reduce((a,x)=>a+x.amount,0))}</div></div></div><div class="card gap"><h3>Process a PurposePay authorization</h3><p class="muted">Never complete a sale unless the authorization is valid and the purchase matches the approved purpose.</p><button class="btn primary" onclick="go('verify')">Verify authorization</button></div>`}
async function completeSale(e){e.preventDefault();try{const r=await api('/transactions/complete',{method:'POST',body:JSON.stringify({transactionId:txid.value,authorizationCode:auth.value,receiptUrl:receipt.value})});toast(`Sale ${r.status.toLowerCase()}`);go('sales')}catch(err){toast(err.message,'error')}}
async function adminPage(){if(page==='operations')return adminOperationsView();if(page==='financial')return adminFinancialIntegrity();if(page==='reconexceptions')return adminReconciliationExceptions();if(page==='disputes')return adminDisputesView();if(page==='reconciliation')return reconciliationView(); if(page==='settlements')return adminSettlementsView();if(page==='kyc')return adminKyc();if(page==='funding')return adminFunding();if(page==='merchants')return adminMerchants();if(page==='transactions')return `<div class="page-title"><h1>Transaction Monitoring</h1></div><div class="card table-wrap">${table(['Reference','Customer','Merchant','Amount','Status','Risk'],(await api('/transactions')).transactions.map(x=>[x.id,x.customer_email,x.merchant_name||'',money(x.amount),badge(x.status),badge(x.risk_status)]))}</div>`;if(page==='risk')return adminRisk();if(page==='audit'){const r=await api('/admin/audit');return `<div class="page-title"><h1>Audit Logs</h1></div><div class="card table-wrap">${table(['Time','Action','Entity','ID'],r.logs.map(x=>[x.created_at,x.action,x.entity_type,x.entity_id||'']))}</div>`}const d=await api('/dashboard');return `<div class="page-title"><h1>Admin Control Center</h1></div><div class="grid"><div class="card"><span class="label">Customers</span><div class="stat">${d.stats.customers}</div></div><div class="card"><span class="label">Pending KYC</span><div class="stat">${d.stats.pendingKyc}</div></div><div class="card"><span class="label">Transactions</span><div class="stat">${d.stats.transactions}</div></div><div class="card"><span class="label">Open risk</span><div class="stat">${d.stats.openRisk}</div></div></div><div class="grid2 gap"><div class="card"><h3>KYC Review</h3><p class="muted">Review identity submissions and record an auditable decision.</p><button class="btn primary" onclick="go('kyc')">Open KYC queue</button></div><div class="card"><h3>Risk & Fraud</h3><p class="muted">Review high-value and flagged transactions.</p><button class="btn secondary" onclick="go('risk')">Open risk center</button></div></div>`}
async function adminReconciliationExceptions(){const r=await api('/admin/reconciliation/exceptions');return '<div class="page-title"><h1>Reconciliation Exceptions</h1></div><div class="card table-wrap">'+table(['Settlement','Merchant','Amount','Settlement','Transaction','Provider Ref','Created'],r.exceptions.map(x=>[x.id,esc(x.merchant_name||''),money(x.amount),badge(x.status),badge(x.transaction_status+' / '+x.settlement_status),esc(x.provider_reference||''),esc(x.created_at)]))+'</div>'+(r.exceptions.length?'':'<div class="card gap">No reconciliation exceptions.</div>')}
async function adminFinancialIntegrity(){const r=await api('/admin/financial-integrity');return '<div class="page-title"><h1>Financial Integrity</h1><button class="btn secondary" onclick="runReconciliation()">Run reconciliation</button></div><div class="grid"><div class="card"><span class="label">Overall status</span><div class="stat">'+(r.healthy?'HEALTHY':'EXCEPTIONS')+'</div></div><div class="card"><span class="label">Ledger entries</span><div class="stat">'+r.ledgerEntries+'</div></div><div class="card"><span class="label">Global imbalance</span><div class="stat">'+money(r.globalLedgerImbalance)+'</div></div><div class="card"><span class="label">Unprocessed webhooks</span><div class="stat">'+r.unprocessedWebhooks+'</div></div></div><div class="card gap"><h3>Wallet mismatches</h3>'+(r.walletMismatches.length?table(['Customer','Wallet','Ledger','Difference'],r.walletMismatches.map(x=>[esc(x.customerId),money(x.walletBalance),money(x.ledgerBalance),money(x.walletBalance-x.ledgerBalance)])):'<p class="muted">No wallet/ledger mismatches.</p>')+'</div><div class="card gap"><h3>Unbalanced transactions</h3>'+(r.unbalancedTransactions.length?table(['Transaction','Imbalance'],r.unbalancedTransactions.map(x=>[esc(x.transactionId),money(x.imbalance)])):'<p class="muted">All transaction ledger entries balance.</p>')+'</div>'}
async function runReconciliation(){try{const r=await api('/admin/reconciliation/run',{method:'POST',body:'{}'});toast('Reconciliation complete: '+r.exceptions+' exception(s)');go('financial')}catch(e){toast(e.message,'error')}}
async function adminOperationsView(){const r=await api('/admin/operations');const alerts=r.alerts.map(x=>'<div class="card gap"><div class="page-title"><div><h3>'+esc(x.title)+'</h3><div class="muted">'+esc(x.type)+' · '+esc(x.created_at)+'</div></div>'+badge(x.severity)+'</div><p>'+esc(x.message)+'</p><div class="actions"><button class="btn secondary" onclick="ackOperationalAlert(\''+x.id+'\')">Acknowledge</button></div></div>').join('');return '<div class="page-title"><h1>Operations Center</h1></div><div class="grid"><div class="card"><span class="label">Open alerts</span><div class="stat">'+r.summary.openAlerts+'</div></div><div class="card"><span class="label">Pending settlements</span><div class="stat">'+r.summary.pendingSettlements+'</div></div><div class="card"><span class="label">Failed settlements</span><div class="stat">'+r.summary.failedSettlements+'</div></div><div class="card"><span class="label">Risk reviews</span><div class="stat">'+r.summary.riskReviews+'</div></div><div class="card"><span class="label">Stale transactions</span><div class="stat">'+r.summary.staleTransactions+'</div></div></div><div class="card gap"><h3>Operational alerts</h3>'+ (alerts||'<p class="muted">No open operational alerts.</p>')+'</div>'}
async function readNotification(id){try{await api('/notifications/read',{method:'POST',body:JSON.stringify({id})});go('notifications')}catch(e){toast(e.message,'error')}}
async function readAllNotifications(){try{await api('/notifications/read-all',{method:'POST',body:'{}'});go('notifications')}catch(e){toast(e.message,'error')}}
async function ackOperationalAlert(id){try{await api('/admin/operations/ack',{method:'POST',body:JSON.stringify({id})});toast('Alert acknowledged');go('operations')}catch(e){toast(e.message,'error')}}
async function adminKyc(){const r=await api('/admin/kyc');return `<div class="page-title"><h1>KYC Review</h1></div>${r.documents.map(x=>`<div class="card gap"><div class="page-title"><div><h3>${esc(x.first_name)} ${esc(x.last_name)}</h3><div class="muted">${esc(x.email)} · ${esc(x.document_type)} · •••••${esc(x.documentNumberLast4||'****')}</div></div>${badge(x.status)}</div><p>Country: ${esc(x.country_of_issue)} · Submitted: ${esc(x.created_at)}</p><div class="actions"><button class="btn success" onclick="reviewKyc('${x.id}','VERIFIED')">Approve</button><button class="btn danger" onclick="reviewKyc('${x.id}','FAILED')">Reject</button></div></div>`).join('')||empty('No KYC submissions.')}`}
async function reviewKyc(id,status){try{await api(`/admin/kyc/${id}/review`,{method:'POST',body:JSON.stringify({status})});toast(`KYC ${status.toLowerCase()}`);go('kyc')}catch(e){toast(e.message,'error')}}
async function adminRisk(){const r=await api('/admin/risk');return `<div class="page-title"><h1>Risk & Fraud</h1></div>${r.alerts.map(x=>`<div class="card gap"><div class="page-title"><div><h3>${esc(x.id)}</h3><div class="muted">${esc(x.customer_email)} · ${esc(x.merchant_name||'')} · ${money(x.amount)}</div></div>${badge(x.risk_status)}</div><p>Purpose: ${esc(x.category)} · Transaction: ${esc(x.id)}</p><button class="btn success" onclick="resolveRisk('${x.id}','CLEAR')">Mark reviewed</button><button class="btn danger" onclick="resolveRisk('${x.id}','BLOCKED')">Block</button></div>`).join('')||empty('No flagged transactions.')}`}
async function resolveRisk(id,status){try{await api('/admin/risk/resolve',{method:'POST',body:JSON.stringify({transactionId:id,status})});toast(`Risk status: ${status}`);go('risk')}catch(e){toast(e.message,'error')}}
async function disputesView(){const r=await api('/disputes');return '<div class="page-title"><h1>Disputes & Refunds</h1></div>'+r.disputes.map(x=>'<div class="card gap"><div class="page-title"><div><h3>'+esc(x.reason)+'</h3><div class="muted">Transaction '+esc(x.transaction_id)+' · '+money(x.amount)+'</div></div>'+badge(x.status)+'</div><p>'+esc(x.details||'No additional details')+'</p></div>').join('')||empty('No disputes filed.')}
async function adminDisputesView(){const r=await api('/disputes');return '<div class="page-title"><h1>Dispute Center</h1></div>'+r.disputes.map(x=>'<div class="card gap"><div class="page-title"><div><h3>'+esc(x.reason)+'</h3><div class="muted">'+esc(x.customer_email||x.customer_id)+' · Transaction '+esc(x.transaction_id)+' · '+money(x.amount)+'</div></div>'+badge(x.status)+'</div><p>'+esc(x.details||'No additional details')+'</p>'+(x.status==='OPEN'?'<div class="actions"><button class="btn success" onclick="resolveDispute(\''+x.id+'\',\'REFUND\')">Issue full refund</button><button class="btn danger" onclick="resolveDispute(\''+x.id+'\',\'REJECTED\')">Reject</button></div>':'')+'</div>').join('')||empty('No disputes.')}
async function resolveDispute(id,outcome){try{await api('/admin/disputes/'+id+'/resolve',{method:'POST',body:JSON.stringify({outcome:outcome,note:outcome==='REFUND'?'Approved refund':'Reviewed and rejected'})});toast('Dispute '+outcome.toLowerCase());go('disputes')}catch(e){toast(e.message,'error')}}
async function viewReceipt(id){try{const r=await api('/transactions/'+encodeURIComponent(id)+'/receipt');const x=r.receipt;document.getElementById('modal').innerHTML='<div class="modal-card"><div class="page-title"><h2>PurposePay Receipt</h2><button class="btn secondary" onclick="closeModal()">Close</button></div><div class="receipt"><h3>'+esc(x.receiptNumber||x.transactionId)+'</h3><p><b>Merchant:</b> '+esc(x.merchant||'')+'</p><p><b>Purpose:</b> '+esc(x.category||'')+'</p><p><b>Project:</b> '+esc(x.project||'')+'</p><p><b>Amount:</b> '+money(x.amount)+'</p><p><b>Status:</b> '+badge(x.status)+'</p><p><b>Date:</b> '+esc(x.createdAt||'')+'</p></div></div>';document.getElementById('modal').classList.add('open')}catch(e){toast(e.message,'error')}}
async function notificationsView(){const r=await api('/notifications');const items=r.notifications.map(n=>'<div class="card gap '+(n.read_at?'':'notice')+'"><div class="page-title"><div><h3>'+esc(n.title)+'</h3><p>'+esc(n.message)+'</p><div class="muted">'+esc(n.created_at)+'</div></div>'+(!n.read_at?'<button class="btn secondary" onclick="readNotification(\''+n.id+'\')">Mark read</button>':'')+'</div></div>').join('');return '<div class="page-title"><div><h1>Notifications</h1><div class="muted">'+r.unread+' unread</div></div><button class="btn secondary" onclick="readAllNotifications()">Mark all read</button></div>'+(items||empty('No notifications.'))}
async function adminSettlementsView(){const r=await api('/settlements');return '<div class="page-title"><h1>Settlement Operations</h1></div><div class="card table-wrap">'+table(['Settlement','Merchant','Amount','Status','Created','Actions'],r.settlements.map(x=>[x.id,esc(x.merchant_name||''),money(x.amount),badge(x.status),esc(x.created_at),x.status==='PENDING'?'<button class="btn secondary" onclick="settleStatus(\''+x.id+'\',\'PROCESSING\')">Process payout</button>':x.status==='PROCESSING'?'<button class="btn success" onclick="settleStatus(\''+x.id+'\',\'PAID\')">Confirm paid</button>':'']))+'</div>'}
async function settleStatus(id,status){try{if(status==='PROCESSING'){await api('/admin/settlements/process',{method:'POST',body:JSON.stringify({settlementId:id})})}else{let ref=prompt('Provider payout reference (optional)')||null;await api('/admin/settlements/'+id+'/status',{method:'POST',body:JSON.stringify({status:status,providerReference:ref})})}toast('Settlement updated');go('settlements')}catch(e){toast(e.message,'error')}}
async function reconciliationView(){const r=await api('/admin/reconciliation');return '<div class="page-title"><h1>Reconciliation</h1></div><div class="grid2"><div class="card"><h3>Transactions</h3>'+table(['Status','Count','Amount'],r.transactions.map(x=>[badge(x.status),x.count,money(x.amount)]))+'</div><div class="card"><h3>Settlements</h3>'+table(['Status','Count','Amount'],r.settlements.map(x=>[badge(x.status),x.count,money(x.amount)]))+'</div><div class="card"><h3>Disputes</h3>'+table(['Status','Count','Amount'],r.disputes.map(x=>[badge(x.status),x.count,money(x.amount)]))+'</div><div class="card"><h3>Refunds</h3>'+table(['Status','Count','Amount'],r.refunds.map(x=>[badge(x.status),x.count,money(x.amount)]))+'</div></div>'}
function table(headers,rows){if(!rows.length)return empty('No records.');return `<table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function empty(msg){return `<div class="empty">${esc(msg)}</div>`}

mount();
async function fundingView(){const params=new URLSearchParams(location.search);const intentId=params.get('intent');let returnNotice='';if(intentId){try{const r=await api('/payments/'+encodeURIComponent(intentId));const p=r.payment;returnNotice='<div class="notice"><b>Payment returned.</b> Reference '+esc(p.provider_reference||p.id)+' · Status '+badge(p.status)+(p.status==='SUCCEEDED'?' · Funds have been credited to your PurposePay balance.':' · Waiting for payment confirmation. Refresh this page to check again.')+'</div>'}catch(e){returnNotice='<div class="notice">We could not find that payment yet. Please check your funding history.</div>'}history.replaceState({},'',location.pathname)}const [w,p]=await Promise.all([api('/wallet'),api('/payments')]);return '<div class="page-title"><h1>Add Funds</h1></div>'+returnNotice+'<div class="grid"><div class="card"><span class="label">Available PurposePay balance</span><div class="stat">'+money(w.availableBalance)+'</div><p class="muted">Funds can be allocated to controlled vouchers. They cannot be withdrawn as unrestricted cash.</p></div><div class="card"><h3>Fund your account</h3><form class="form" onsubmit="startFunding(event)"><div class="field"><label>Amount (GH₵)</label><input id="fundAmount" type="number" min="1" step="1" required value="100"></div><button class="btn primary">Continue to payment</button></form></div></div><div class="card gap"><h3>Funding history</h3>'+table(['Reference','Amount','Provider','Status','Created'],p.payments.map(x=>[x.reference,money(x.amount),x.provider,badge(x.status),esc(x.created_at)]))+'</div>'}
async function startFunding(e){e.preventDefault();try{const r=await api('/payments/intent',{method:'POST',body:JSON.stringify({amount:Number(fundAmount.value)})});if(r.checkoutUrl){window.location.href=r.checkoutUrl;return}if(r.provider==='demo'){await api('/payments/'+encodeURIComponent(r.id)+'/demo-complete',{method:'POST'});toast('Demo payment completed and wallet credited.');go('funding');return}toast('Payment intent created.');go('funding')}catch(e){toast(e.message,'error')}}
async function adminFunding(){const r=await api('/payments');return `<div class="page-title"><h1>Payment Funding</h1></div><div class="card table-wrap">${table(['Customer','Reference','Amount','Provider','Status','Created'],r.payments.map(x=>[esc(x.customer_email||''),x.reference,money(x.amount),x.provider,badge(x.status),esc(x.created_at)]))}</div>`}
async function merchantPayoutView(){let r;try{r=await api('/merchants/payout-profile')}catch(e){return '<div class="page-title"><h1>Payout Account</h1></div><div class="notice">'+esc(e.message)+'</div>'}return '<div class="page-title"><h1>Payout Account</h1></div><div class="card"><h3>Current payout setup</h3><p>Provider: '+esc(r.profile.provider||'manual')+'</p><p>Account: '+esc(r.profile.accountName||'Not configured')+(r.profile.accountNumberMasked?' · ending '+esc(r.profile.accountNumberMasked):'')+'</p></div><div class="card gap"><h3>Set or update payout account</h3><p class="muted">PurposePay stores only the payout details needed for settlement. Never enter your online-banking password or PIN.</p><form class="form" onsubmit="savePayoutProfile(event)"><div class="field"><label>Account name</label><input id="paName" required value="'+esc(r.profile.accountName||'')+'"></div><div class="field"><label>Bank code</label><input id="paBank" required value="'+esc(r.profile.bankCode||'')+'"></div><div class="field"><label>Account number</label><input id="paNumber" inputmode="numeric" required></div><button class="btn primary">Save payout account</button></form></div>'}
async function savePayoutProfile(e){e.preventDefault();try{const r=await api('/merchants/payout-profile',{method:'POST',body:JSON.stringify({accountName:paName.value,bankCode:paBank.value,accountNumber:paNumber.value})});toast('Payout account configured for '+r.provider);go('payout')}catch(err){toast(err.message,'error')}}
async function merchantOnboardingView(){const r=await api('/merchants/me');return `<div class="page-title"><h1>Business Onboarding</h1></div><div class="card"><h3>Merchant status</h3><p>Application: ${r.application?badge(r.application.status):'Not submitted'}</p>${r.application?`<p class="muted">${esc(r.application.business_name)} · ${esc(r.application.category)}</p>`:`<form class="form" onsubmit="applyMerchant(event)"><div class="field"><label>Business name</label><input id="mbn" required></div><div class="row"><div class="field"><label>Business category</label><input id="mbc" required placeholder="Building Materials"></div><div class="field"><label>Business registration</label><input id="mbr"></div></div><div class="field"><label>Contact phone</label><input id="mbp"></div><button class="btn primary">Submit business application</button></form>`}</div>${r.merchant?`<div class="card gap"><h3>Approved merchant profile</h3><p><b>${esc(r.merchant.name)}</b> · ${badge(r.merchant.status)}</p><p>Settlement: ${badge(r.merchant.settlement_status)}</p></div>`:''}`}
async function applyMerchant(e){e.preventDefault();try{await api('/merchants/apply',{method:'POST',body:JSON.stringify({businessName:mbn.value,category:mbc.value,businessRegistration:mbr.value,contactPhone:mbp.value})});toast('Merchant application submitted');go('onboarding')}catch(e){toast(e.message,'error')}}
async function adminMerchants(){const r=await api('/admin/merchants');return `<div class="page-title"><h1>Merchant Onboarding</h1></div>${r.applications.map(x=>`<div class="card gap"><div class="page-title"><div><h3>${esc(x.business_name)}</h3><div class="muted">${esc(x.email)} · ${esc(x.category)} · KYC ${esc(x.kyc_status)}</div></div>${badge(x.status)}</div><p>Registration: ${esc(x.business_registration||'Not provided')} · Phone: ${esc(x.contact_phone||'')}</p>${x.status==='PENDING'?`<div class="actions"><button class="btn success" onclick="reviewMerchant('${x.id}','APPROVED')">Approve</button><button class="btn danger" onclick="reviewMerchant('${x.id}','REJECTED')">Reject</button></div>`:''}</div>`).join('')||empty('No merchant applications.')}`}
async function reviewMerchant(id,status){try{await api('/admin/merchants/'+id+'/review',{method:'POST',body:JSON.stringify({status})});toast('Merchant '+status.toLowerCase());go('merchants')}catch(e){toast(e.message,'error')}}

mount();
