import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import pg from 'pg';
import { loadIdempotency, saveIdempotency, publicErrorResponse } from './request-safety.js';
const { Pool } = pg;

const PORT=Number(process.env.PORT||8787);
const JWT_SECRET=process.env.PURPOSEPAY_JWT_SECRET;
const ORIGIN=process.env.PURPOSEPAY_ALLOWED_ORIGIN||'';
const production=process.env.NODE_ENV==='production';
if(production&&(!JWT_SECRET||JWT_SECRET.length<32))throw new Error('PURPOSEPAY_JWT_SECRET must be at least 32 characters in production');
const SECRET=JWT_SECRET||crypto.createHash('sha256').update('purposepay-local-development-secret').digest('hex');
const DATABASE_URL=process.env.DATABASE_URL;
if(production&&!DATABASE_URL)throw new Error('DATABASE_URL is required in production');
const pool=new Pool({connectionString:DATABASE_URL||'postgres://localhost/purposepay',max:5,ssl:DATABASE_URL&&/sslmode=require/i.test(DATABASE_URL)?{rejectUnauthorized:false}:undefined});
const ROOT=path.dirname(fileURLToPath(import.meta.url));
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon'};
const id=p=>`${p}_${crypto.randomUUID()}`;
const loginAttempts=new Map();
const q=(sql,params=[])=>pool.query(sql,params);
const role=(me,...roles)=>!!me&&roles.includes(me.role);
const safe=u=>({id:u.id,email:u.email,role:u.role,firstName:u.first_name,lastName:u.last_name,phone:u.phone,kycStatus:u.kyc_status,status:u.status,createdAt:u.created_at});
function limitLogin(email){const now=Date.now();let x=loginAttempts.get(email)||{count:0,window:now};if(now-x.window>900000)x={count:0,window:now};x.count++;loginAttempts.set(email,x);return x.count<=10}
function token(u){return jwt.sign({sub:u.id,role:u.role,email:u.email},SECRET,{expiresIn:'8h',issuer:'purposepay',audience:'purposepay-web'})}
function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;try{return jwt.verify(h.slice(7),SECRET,{issuer:'purposepay',audience:'purposepay-web'})}catch{return null}}
function out(res,status,body){const h={'content-type':'application/json','access-control-allow-headers':'Content-Type, Authorization, Idempotency-Key','access-control-allow-methods':'GET,POST,PATCH,OPTIONS'};if(ORIGIN)h['access-control-allow-origin']=ORIGIN;res.writeHead(status,h);res.end(JSON.stringify(body))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1000000)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});req.on('error',reject)})}
async function audit(actor,action,type,entity,meta={}){await q('INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,metadata_json) VALUES($1,$2,$3,$4,$5,$6)',[id('AUD'),actor||null,action,type,entity||null,JSON.stringify(meta)])}

async function init(){
 await q(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL,first_name TEXT,last_name TEXT,phone TEXT,kyc_status TEXT NOT NULL DEFAULT 'UNVERIFIED',status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS kyc_documents(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),document_type TEXT NOT NULL,document_number TEXT NOT NULL,country_of_issue TEXT NOT NULL,issue_date TEXT,expiry_date TEXT,file_front_url TEXT,file_back_url TEXT,selfie_url TEXT,status TEXT NOT NULL DEFAULT 'UNDER_REVIEW',review_note TEXT,reviewed_by TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),reviewed_at TIMESTAMPTZ);
 CREATE TABLE IF NOT EXISTS merchants(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING',categories_json TEXT NOT NULL DEFAULT '[]',settlement_status TEXT NOT NULL DEFAULT 'PENDING',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS schools(id TEXT PRIMARY KEY,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES users(id),name TEXT NOT NULL,location TEXT NOT NULL,contractor_name TEXT,contractor_phone TEXT,description TEXT,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS vouchers(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),category TEXT NOT NULL,initial_amount BIGINT NOT NULL CHECK(initial_amount>0),used_amount BIGINT NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS transactions(id TEXT PRIMARY KEY,voucher_id TEXT REFERENCES vouchers(id),project_id TEXT REFERENCES projects(id),customer_id TEXT NOT NULL REFERENCES users(id),merchant_id TEXT REFERENCES merchants(id),category TEXT,amount BIGINT NOT NULL CHECK(amount>0),status TEXT NOT NULL DEFAULT 'PENDING',authorization_code TEXT UNIQUE,receipt_url TEXT,risk_status TEXT NOT NULL DEFAULT 'CLEAR',settlement_status TEXT NOT NULL DEFAULT 'PENDING',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),completed_at TIMESTAMPTZ);
 CREATE TABLE IF NOT EXISTS school_payments(id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES users(id),school_id TEXT NOT NULL REFERENCES schools(id),student_name TEXT NOT NULL,student_id TEXT,term TEXT,amount BIGINT NOT NULL CHECK(amount>0),status TEXT NOT NULL DEFAULT 'PENDING',receipt_url TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),completed_at TIMESTAMPTZ);
 CREATE TABLE IF NOT EXISTS idempotency_keys(key TEXT PRIMARY KEY,user_id TEXT NOT NULL,request_hash TEXT NOT NULL,response_json TEXT NOT NULL,status_code INTEGER NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS audit_logs(id TEXT PRIMARY KEY,actor_user_id TEXT,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,metadata_json TEXT NOT NULL DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE INDEX IF NOT EXISTS idx_projects_customer ON projects(customer_id);
 CREATE INDEX IF NOT EXISTS idx_vouchers_project ON vouchers(project_id);
 CREATE INDEX IF NOT EXISTS idx_transactions_customer ON transactions(customer_id);
 CREATE INDEX IF NOT EXISTS idx_transactions_status ON transactions(status);
 CREATE INDEX IF NOT EXISTS idx_kyc_status ON kyc_documents(status);`);
 await seed();
}
async function seed(){
 let r=await q("SELECT id FROM users WHERE email='admin@purposepay.test'");if(!r.rows[0]){const uid=id('USR');await q('INSERT INTO users(id,email,password_hash,role,first_name,last_name,kyc_status) VALUES($1,$2,$3,$4,$5,$6,$7)',[uid,'admin@purposepay.test',await bcrypt.hash('Admin12345!',12),'ADMIN','PurposePay','Admin','VERIFIED'])}
 r=await q("SELECT id FROM users WHERE email='demo@purposepay.test'");if(r.rows[0])return;
 const uid=id('USR'),mid=id('MER'),muid=id('USR'),cuid=id('USR'),sid=id('SCH'),pid=id('PRJ'),vid=id('VCH'),tx=id('TXN');
 await q('INSERT INTO users(id,email,password_hash,role,first_name,last_name,phone,kyc_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[uid,'demo@purposepay.test',await bcrypt.hash('Demo12345!',12),'CUSTOMER','Demo','Customer','+233200000000','VERIFIED']);
 await q('INSERT INTO users(id,email,password_hash,role,first_name,last_name,kyc_status) VALUES($1,$2,$3,$4,$5,$6,$7)',[muid,'merchant@purposepay.test',await bcrypt.hash('Merchant12345!',12),'MERCHANT','ABC','Merchant','VERIFIED']);
 await q('INSERT INTO merchants(id,user_id,name,status,categories_json,settlement_status) VALUES($1,$2,$3,$4,$5,$6)',[mid,muid,'ABC Building Materials','APPROVED',JSON.stringify(['Cement','Blocks','Steel','Roofing']),'PENDING']);
 await q('INSERT INTO users(id,email,password_hash,role,first_name,last_name,phone,kyc_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[cuid,'contractor@purposepay.test',await bcrypt.hash('Contractor12345!',12),'CONTRACTOR','Kwame','Mensah','+233200000001','VERIFIED']);
 await q('INSERT INTO schools(id,name,status) VALUES($1,$2,$3)',[sid,'Accra International School','APPROVED']);
 await q('INSERT INTO projects(id,customer_id,name,location,contractor_name,contractor_phone,description) VALUES($1,$2,$3,$4,$5,$6,$7)',[pid,uid,'Johnson Family House','Accra','Kwame Mensah','+233200000001','Family house construction']);
 await q('INSERT INTO vouchers(id,project_id,category,initial_amount,used_amount,status) VALUES($1,$2,$3,$4,$5,$6)',[vid,pid,'Cement',20000,8000,'PARTIALLY_USED']);
 await q('INSERT INTO transactions(id,voucher_id,project_id,customer_id,merchant_id,category,amount,status,authorization_code,risk_status,settlement_status,completed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,NOW())',[tx,vid,pid,uid,mid,'Cement',8000,'COMPLETED','DEMOAUTH','REVIEW','PENDING']);
 await audit(uid,'SEED_DEMO','SYSTEM',null,{transaction:tx});
}
async function main(req,res){
 if(req.method==='OPTIONS')return out(res,204,{});
 const urlPath=req.url.split('?')[0],parts=urlPath.split('/').filter(Boolean),route=parts.join('/');
 try{
  if(req.method==='GET'&&route==='api/health'){const r=await q('SELECT 1 AS ok');return out(res,200,{ok:r.rows[0].ok===1,service:'purposepay-api',version:'0.7.0',database:'postgres'})}
  if(req.method==='GET'&&!route.startsWith('api/')){const webRoot=path.resolve(ROOT,'..'),requested=route||'index.html',candidate=path.resolve(webRoot,requested);const inside=candidate===webRoot||candidate.startsWith(`${webRoot}${path.sep}`);const f=inside&&fs.existsSync(candidate)&&fs.statSync(candidate).isFile()?candidate:path.join(webRoot,'index.html');res.writeHead(200,{'content-type':MIME[path.extname(f)]||'text/html'});return res.end(fs.readFileSync(f))}
  if(req.method==='POST'&&route==='api/auth/register'){const b=await body(req);if(!b.email||!b.password||!b.firstName||!b.lastName||!b.documentType||!b.documentNumber||!b.countryOfIssue)return out(res,400,{error:'Name, email, password and government ID details are required'});if(String(b.password).length<8)return out(res,400,{error:'Password must be at least 8 characters'});if(String(b.documentNumber).trim().length<4)return out(res,400,{error:'Government ID number is too short'});const email=b.email.trim().toLowerCase();if((await q('SELECT 1 FROM users WHERE email=$1',[email])).rows[0])return out(res,409,{error:'Email already registered'});const client=await pool.connect();let u;try{await client.query('BEGIN');const uid=id('USR');await client.query('INSERT INTO users(id,email,password_hash,role,first_name,last_name,phone,kyc_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[uid,email,await bcrypt.hash(b.password,12),'CUSTOMER',b.firstName.trim(),b.lastName.trim(),b.phone||null,'UNDER_REVIEW']);const kid=id('KYC');await client.query('INSERT INTO kyc_documents(id,user_id,document_type,document_number,country_of_issue,issue_date,expiry_date,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[kid,uid,String(b.documentType).trim(),String(b.documentNumber).trim(),String(b.countryOfIssue).trim(),b.issueDate||null,b.expiryDate||null,'UNDER_REVIEW']);await client.query('INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,metadata_json) VALUES($1,$2,$3,$4,$5,$6)',[id('AUD'),uid,'REGISTER','USER',uid,JSON.stringify({kycId:kid})]);u=(await client.query('SELECT * FROM users WHERE id=$1',[uid])).rows[0];await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}return out(res,201,{user:safe(u),token:token(u),kyc:{status:'UNDER_REVIEW'}})}
  if(req.method==='POST'&&route==='api/auth/login'){const b=await body(req),email=(b.email||'').trim().toLowerCase();if(!limitLogin(email))return out(res,429,{error:'Too many login attempts. Try again later.'});const u=(await q('SELECT * FROM users WHERE email=$1',[email])).rows[0];if(!u||!(await bcrypt.compare(b.password||'',u.password_hash)))return out(res,401,{error:'Invalid email or password'});return out(res,200,{user:safe(u),token:token(u)})}
  const me=auth(req);if(!me)return out(res,401,{error:'Authentication required'});
  if(req.method==='GET'&&route==='api/me'){const u=(await q('SELECT * FROM users WHERE id=$1',[me.sub])).rows[0];return out(res,200,{user:safe(u)})}
  if(req.method==='POST'&&route==='api/kyc/submit'){if(!role(me,'CUSTOMER'))return out(res,403,{error:'Customer role required'});const b=await body(req);if(!b.documentType||!b.documentNumber||!b.countryOfIssue)return out(res,400,{error:'Document type, number and country of issue are required'});const kid=id('KYC');await q('INSERT INTO kyc_documents(id,user_id,document_type,document_number,country_of_issue,issue_date,expiry_date,file_front_url,file_back_url,selfie_url) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[kid,me.sub,b.documentType,b.documentNumber,b.countryOfIssue,b.issueDate||null,b.expiryDate||null,b.fileFrontUrl||null,b.fileBackUrl||null,b.selfieUrl||null]);await q('UPDATE users SET kyc_status=$1 WHERE id=$2',['UNDER_REVIEW',me.sub]);await audit(me.sub,'KYC_SUBMITTED','KYC',kid);return out(res,201,{id:kid,status:'UNDER_REVIEW'})}
  if(req.method==='GET'&&route==='api/kyc/me'){const k=(await q('SELECT * FROM kyc_documents WHERE user_id=$1 ORDER BY created_at DESC LIMIT 1',[me.sub])).rows[0];return out(res,200,{kyc:k||null})}
  if(req.method==='GET'&&route==='api/dashboard'){if(role(me,'CUSTOMER')){const [p,v,t,s]=await Promise.all([q('SELECT COUNT(*)::int n FROM projects WHERE customer_id=$1',[me.sub]),q('SELECT COUNT(*)::int n FROM vouchers v JOIN projects p ON p.id=v.project_id WHERE p.customer_id=$1',[me.sub]),q('SELECT COUNT(*)::int n FROM transactions WHERE customer_id=$1',[me.sub]),q('SELECT COUNT(*)::int n FROM school_payments WHERE customer_id=$1',[me.sub])]);return out(res,200,{stats:{projects:p.rows[0].n,vouchers:v.rows[0].n,transactions:t.rows[0].n,schoolPayments:s.rows[0].n}})}if(role(me,'ADMIN')){const [c,k,t,r]=await Promise.all([q("SELECT COUNT(*)::int n FROM users WHERE role='CUSTOMER'"),q("SELECT COUNT(*)::int n FROM users WHERE kyc_status='UNDER_REVIEW'"),q('SELECT COUNT(*)::int n FROM transactions'),q("SELECT COUNT(*)::int n FROM transactions WHERE risk_status='REVIEW'")]);return out(res,200,{stats:{customers:c.rows[0].n,pendingKyc:k.rows[0].n,transactions:t.rows[0].n,openRisk:r.rows[0].n}})}if(role(me,'MERCHANT')){const r=await q('SELECT COUNT(*)::int n FROM transactions WHERE merchant_id=(SELECT id FROM merchants WHERE user_id=$1)',[me.sub]);return out(res,200,{stats:{sales:r.rows[0].n}})}return out(res,200,{stats:{}})}
  if(req.method==='POST'&&route==='api/projects'){if(!role(me,'CUSTOMER'))return out(res,403,{error:'Customer role required'});const b=await body(req),u=(await q('SELECT kyc_status FROM users WHERE id=$1',[me.sub])).rows[0];if(u?.kyc_status!=='VERIFIED')return out(res,403,{error:'Complete identity verification before creating a funded project'});if(!b.name||!b.location)return out(res,400,{error:'Project name and location are required'});const pid=id('PRJ');await q('INSERT INTO projects(id,customer_id,name,location,contractor_name,contractor_phone,description) VALUES($1,$2,$3,$4,$5,$6,$7)',[pid,me.sub,b.name,b.location,b.contractorName||null,b.contractorPhone||null,b.description||null]);await audit(me.sub,'CREATE','PROJECT',pid);return out(res,201,{id:pid,status:'ACTIVE'})}
  if(req.method==='GET'&&route==='api/projects'){if(role(me,'CUSTOMER'))return out(res,200,{projects:(await q('SELECT * FROM projects WHERE customer_id=$1 ORDER BY created_at DESC',[me.sub])).rows});if(role(me,'ADMIN'))return out(res,200,{projects:(await q('SELECT p.*,u.email customer_email FROM projects p JOIN users u ON u.id=p.customer_id ORDER BY p.created_at DESC')).rows});return out(res,403,{error:'Not authorized'})}
  if(req.method==='POST'&&route==='api/vouchers'){if(!role(me,'CUSTOMER'))return out(res,403,{error:'Customer role required'});const u=(await q('SELECT kyc_status FROM users WHERE id=$1',[me.sub])).rows[0];if(u?.kyc_status!=='VERIFIED')return out(res,403,{error:'Complete identity verification before creating a voucher'});const b=await body(req),p=(await q('SELECT * FROM projects WHERE id=$1 AND customer_id=$2',[b.projectId,me.sub])).rows[0];if(!p)return out(res,404,{error:'Project not found'});if(!b.category||!Number.isInteger(b.amount)||b.amount<=0)return out(res,400,{error:'Category and positive integer amount are required'});const vid=id('VCH');await q('INSERT INTO vouchers(id,project_id,category,initial_amount) VALUES($1,$2,$3,$4)',[vid,p.id,b.category,b.amount]);await audit(me.sub,'CREATE','VOUCHER',vid,{amount:b.amount,category:b.category});return out(res,201,{id:vid,code:`PP-BLD-${vid.slice(-8).toUpperCase()}`,status:'ACTIVE',category:b.category,initialAmount:b.amount,usedAmount:0,remainingAmount:b.amount})}
  if(req.method==='GET'&&route==='api/vouchers'){let rows=[];if(role(me,'CUSTOMER'))rows=(await q('SELECT v.*,p.name project_name FROM vouchers v JOIN projects p ON p.id=v.project_id WHERE p.customer_id=$1 ORDER BY v.created_at DESC',[me.sub])).rows;else if(role(me,'CONTRACTOR'))rows=(await q("SELECT v.*,p.name project_name FROM vouchers v JOIN projects p ON p.id=v.project_id WHERE p.contractor_phone=(SELECT phone FROM users WHERE id=$1) OR lower(p.contractor_name)=lower((SELECT trim(first_name||' '||last_name) FROM users WHERE id=$1)) ORDER BY v.created_at DESC",[me.sub])).rows;else if(role(me,'ADMIN'))rows=(await q('SELECT v.*,p.name project_name,u.email customer_email FROM vouchers v JOIN projects p ON p.id=v.project_id JOIN users u ON u.id=p.customer_id ORDER BY v.created_at DESC')).rows;return out(res,200,{vouchers:rows.map(v=>({...v,initial_amount:Number(v.initial_amount),used_amount:Number(v.used_amount),remaining_amount:Number(v.initial_amount)-Number(v.used_amount)}))})}
  if(req.method==='GET'&&route==='api/merchants'){const rows=(await q("SELECT * FROM merchants WHERE status='APPROVED' ORDER BY name")).rows.map(m=>({...m,categories:JSON.parse(m.categories_json||'[]')}));return out(res,200,{merchants:rows})}
  if(req.method==='GET'&&route==='api/schools')return out(res,200,{schools:(await q("SELECT * FROM schools WHERE status='APPROVED' ORDER BY name")).rows})
    if(req.method==='POST'&&route==='api/transactions/authorize'){if(!role(me,'CUSTOMER','CONTRACTOR'))return out(res,403,{error:'Customer or contractor role required'});const b=await body(req),ir=await loadIdempotency(req,me.sub,b,q);if(ir?.status)return out(res,ir.status,ir.body);let v;if(role(me,'CUSTOMER'))v=(await q('SELECT v.*,p.customer_id FROM vouchers v JOIN projects p ON p.id=v.project_id WHERE v.id=$1 AND p.customer_id=$2',[b.voucherId,me.sub])).rows[0];else v=(await q("SELECT v.*,p.customer_id FROM vouchers v JOIN projects p ON p.id=v.project_id WHERE v.id=$1 AND (p.contractor_phone=(SELECT phone FROM users WHERE id=$2) OR lower(p.contractor_name)=lower((SELECT trim(first_name||' '||last_name) FROM users WHERE id=$2)))",[b.voucherId,me.sub])).rows[0];if(!v)return out(res,404,{error:'Voucher not found'});const m=(await q("SELECT * FROM merchants WHERE id=$1 AND status='APPROVED'",[b.merchantId])).rows[0];if(!m)return out(res,400,{error:'Merchant not approved'});const cats=JSON.parse(m.categories_json||'[]');if(cats.length&&!cats.includes(v.category))return out(res,400,{error:'Merchant is not approved for this voucher category'});const remaining=Number(v.initial_amount)-Number(v.used_amount);if(!Number.isInteger(b.amount)||b.amount<=0||b.amount>remaining)return out(res,400,{error:'Amount exceeds voucher balance'});const tx=id('TXN'),code=crypto.randomBytes(6).toString('hex').toUpperCase(),risk=b.amount>=5000?'REVIEW':'CLEAR';await q('INSERT INTO transactions(id,voucher_id,project_id,customer_id,merchant_id,category,amount,status,authorization_code,risk_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[tx,v.id,v.project_id,v.customer_id,m.id,v.category,b.amount,'AUTHORIZED',code,risk]);await audit(me.sub,'AUTHORIZE_PURCHASE','TRANSACTION',tx,{amount:b.amount,merchant:m.name});const response={transactionId:tx,authorizationCode:code,status:'AUTHORIZED',amount:b.amount,riskStatus:risk};await saveIdempotency(ir,me.sub,201,response,q);return out(res,201,response)}
  if(req.method==='GET'&&route==='api/transactions'){let rows;if(role(me,'CUSTOMER'))rows=(await q('SELECT t.*,m.name merchant_name,p.name project_name FROM transactions t LEFT JOIN merchants m ON m.id=t.merchant_id LEFT JOIN projects p ON p.id=t.project_id WHERE t.customer_id=$1 ORDER BY t.created_at DESC',[me.sub])).rows;else if(role(me,'MERCHANT'))rows=(await q('SELECT t.*,m.name merchant_name,p.name project_name FROM transactions t JOIN merchants m ON m.id=t.merchant_id LEFT JOIN projects p ON p.id=t.project_id WHERE m.user_id=$1 ORDER BY t.created_at DESC',[me.sub])).rows;else if(role(me,'ADMIN'))rows=(await q('SELECT t.*,m.name merchant_name,p.name project_name,u.email customer_email FROM transactions t LEFT JOIN merchants m ON m.id=t.merchant_id LEFT JOIN projects p ON p.id=t.project_id JOIN users u ON u.id=t.customer_id ORDER BY t.created_at DESC')).rows;else return out(res,403,{error:'Not authorized'});rows=rows.map(x=>({...x,amount:Number(x.amount)}));return out(res,200,{transactions:rows})}
    if(req.method==='POST'&&route==='api/transactions/complete'){if(!role(me,'MERCHANT','ADMIN'))return out(res,403,{error:'Merchant or admin role required'});const b=await body(req),ir=await loadIdempotency(req,me.sub,b,q),client=await pool.connect();try{if(ir?.status)return out(res,ir.status,ir.body);await client.query('BEGIN');let sql='SELECT t.* FROM transactions t JOIN merchants m ON m.id=t.merchant_id WHERE t.id=$1 AND t.authorization_code=$2 AND m.user_id=$3 FOR UPDATE',params=[b.transactionId,b.authorizationCode,me.sub];if(role(me,'ADMIN')){sql='SELECT * FROM transactions WHERE id=$1 AND authorization_code=$2 FOR UPDATE';params=[b.transactionId,b.authorizationCode]}const tx=(await client.query(sql,params)).rows[0];if(!tx){await client.query('ROLLBACK');return out(res,404,{error:'Authorization not found'})}if(tx.risk_status==='BLOCKED'){await client.query('ROLLBACK');return out(res,403,{error:'Transaction is blocked by risk controls'})}if(tx.status!=='AUTHORIZED'){await client.query('ROLLBACK');return out(res,409,{error:'Transaction is not authorized'})}const v=(await client.query('SELECT * FROM vouchers WHERE id=$1 FOR UPDATE',[tx.voucher_id])).rows[0];if(!v||Number(tx.amount)>Number(v.initial_amount)-Number(v.used_amount))throw Error('Voucher balance changed');const used=Number(v.used_amount)+Number(tx.amount);await client.query('UPDATE vouchers SET used_amount=$1,status=$2 WHERE id=$3',[used,used>=Number(v.initial_amount)?'USED':'PARTIALLY_USED',v.id]);await client.query('UPDATE transactions SET status=$1,receipt_url=$2,settlement_status=$3,completed_at=NOW() WHERE id=$4',['COMPLETED',b.receiptUrl||null,'PENDING',tx.id]);await client.query('COMMIT');await audit(me.sub,'COMPLETE_PURCHASE','TRANSACTION',tx.id,{receiptUrl:b.receiptUrl||null});const response={transactionId:tx.id,status:'COMPLETED'};await saveIdempotency(ir,me.sub,200,response,q);return out(res,200,response)}catch(e){await client.query('ROLLBACK').catch(()=>{});throw e}finally{client.release()}}
    if(req.method==='POST'&&route==='api/schools/payments'){if(!role(me,'CUSTOMER'))return out(res,403,{error:'Customer role required'});const kycUser=(await q('SELECT kyc_status FROM users WHERE id=$1',[me.sub])).rows[0];if(kycUser?.kyc_status!=='VERIFIED')return out(res,403,{error:'Complete identity verification before making a school payment'});const b=await body(req),ir=await loadIdempotency(req,me.sub,b,q);if(ir?.status)return out(res,ir.status,ir.body);const s=(await q("SELECT * FROM schools WHERE id=$1 AND status='APPROVED'",[b.schoolId])).rows[0];if(!s)return out(res,400,{error:'School not approved'});if(!b.studentName||!Number.isInteger(b.amount)||b.amount<=0)return out(res,400,{error:'Student name and positive integer amount are required'});const sp=id('SCH');await q('INSERT INTO school_payments(id,customer_id,school_id,student_name,student_id,term,amount) VALUES($1,$2,$3,$4,$5,$6,$7)',[sp,me.sub,s.id,b.studentName,b.studentId||null,b.term||null,b.amount]);await audit(me.sub,'CREATE','SCHOOL_PAYMENT',sp,{amount:b.amount,school:s.name});const response={id:sp,status:'PENDING',school:s.name};await saveIdempotency(ir,me.sub,201,response,q);return out(res,201,response)}
  if(req.method==='GET'&&route==='api/schools/payments'){const rows=role(me,'CUSTOMER')?(await q('SELECT sp.*,s.name school_name FROM school_payments sp JOIN schools s ON s.id=sp.school_id WHERE sp.customer_id=$1 ORDER BY sp.created_at DESC',[me.sub])).rows:role(me,'ADMIN')?(await q('SELECT sp.*,s.name school_name,u.email customer_email FROM school_payments sp JOIN schools s ON s.id=sp.school_id JOIN users u ON u.id=sp.customer_id ORDER BY sp.created_at DESC')).rows:[];return out(res,200,{payments:rows})}
  if(req.method==='GET'&&route==='api/admin/kyc'){if(!role(me,'ADMIN'))return out(res,403,{error:'Admin role required'});return out(res,200,{documents:(await q('SELECT k.*,u.email,u.first_name,u.last_name,u.kyc_status FROM kyc_documents k JOIN users u ON u.id=k.user_id ORDER BY k.created_at DESC')).rows})}
  if(req.method==='POST'&&parts[0]==='api'&&parts[1]==='admin'&&parts[2]==='kyc'&&parts[4]==='review'){if(!role(me,'ADMIN'))return out(res,403,{error:'Admin role required'});const b=await body(req),k=(await q('SELECT * FROM kyc_documents WHERE id=$1',[parts[3]])).rows[0];if(!k)return out(res,404,{error:'KYC document not found'});const status=b.status==='VERIFIED'?'VERIFIED':'VERIFICATION_FAILED';await q('UPDATE kyc_documents SET status=$1,review_note=$2,reviewed_by=$3,reviewed_at=NOW() WHERE id=$4',[status,b.note||null,me.sub,parts[3]]);await q('UPDATE users SET kyc_status=$1 WHERE id=$2',[status,k.user_id]);await audit(me.sub,'KYC_REVIEW','KYC',parts[3],{status});return out(res,200,{id:parts[3],status})}
  if(req.method==='GET'&&route==='api/admin/risk'){if(!role(me,'ADMIN'))return out(res,403,{error:'Admin role required'});return out(res,200,{alerts:(await q("SELECT t.*,m.name merchant_name,u.email customer_email FROM transactions t LEFT JOIN merchants m ON m.id=t.merchant_id JOIN users u ON u.id=t.customer_id WHERE t.risk_status='REVIEW' ORDER BY t.created_at DESC")).rows})}
  if(req.method==='POST'&&route==='api/admin/risk/resolve'){if(!role(me,'ADMIN'))return out(res,403,{error:'Admin role required'});const b=await body(req);await q('UPDATE transactions SET risk_status=$1 WHERE id=$2',[b.status==='BLOCKED'?'BLOCKED':'CLEAR',b.transactionId]);await audit(me.sub,'RISK_REVIEW','TRANSACTION',b.transactionId,{status:b.status});return out(res,200,{status:b.status})}
  if(req.method==='GET'&&route==='api/admin/audit'){if(!role(me,'ADMIN'))return out(res,403,{error:'Admin role required'});return out(res,200,{logs:(await q('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 200')).rows})}
  return out(res,404,{error:'Route not found'})
 }catch(e){console.error(e);const publicError=publicErrorResponse(e);return out(res,publicError.status,publicError.body)}
}
await init();
http.createServer((req,res)=>main(req,res)).listen(PORT,'0.0.0.0',()=>console.log(`PurposePay API v0.7 listening on 0.0.0.0:${PORT}`));